# Site settings

author: sdfjklmin
email: sdfjklmin@gmail.com
twitter_username: twitter
github_username:  github
googleplus_username: google

head-title: FengChenMinstrel
title: FengChenMinstrel

baseurl: ""    # the subpath of your site, "/blog"
url: ""

# footer 
description: "I know that what I'm doing looks stupid, but I'm a big boy and really want to do this."

# 标语
favo: "春梦随云散，飞花逐水流。闻理若似悟，遇境则乱迷。"
descrpt: "“巧者劳而智者忧，无能者无所求，饱食而遨游，泛若不系之舟”  ——《南华经》"

# 右侧栏小标题
tocTopTag: "h4"

# git talk 设置
gitalk:
  clientID: 'c371df439b8a4c058768'
  clientSecret: 'fc7b8087950adfcc0019d967048edefcff839d37'
  repo: 'sdfjklmin.github.io.comment'
  owner: 'sdfjklmin'
  admin: 'sdfjklmin'

#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

#permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]

plugins: [jekyll-paginate]
#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

